feat: adds search suggestions
datadeling/datafabrikken-portal pull request #109
Opened 2021-11-15 15:51 UTC by matsjs

Close #96

2021-11-16 10:02 UTC, oyvindis commented on src/components/with-suggestions/redux/reducer.ts
> +        .set('searchSuggestions', fromJS(action.payload.suggestions))
Jeg ser ikke at det er nødvendig å lagre suggestions to ganger, det vil vel holde å bare ha "cachedSuggestions" ?

2021-11-16 10:06 UTC, oyvindis commented on src/entrypoints/main/router/pages/datasets-page/index.tsx
> +              onChange={e => {
Definere funksjonen over som f.eks. const searchSuggestion ....

2021-11-16 10:09 UTC, oyvindis commented on src/entrypoints/main/router/pages/datasets-page/index.tsx
> +              onChange={e => {
kan f.eks. ha med type (e: FormEvent<HTMLFormElement>)

2021-11-16 10:11 UTC, oyvindis commented on src/entrypoints/main/router/pages/datasets-page/index.tsx
> +                if (!cachedSuggestions?.[e.target.value]) {
Jeg tror uansett ikke du får noe treff på bare ett enkelt tegn, så du kan ta med en betingelse at lengden på søkeordet må være > 1 for at det gjøres et kall.

2021-11-16 10:15 UTC, oyvindis commented on src/components/with-suggestions/index.tsx
> +  searchSuggestions?: SearchSuggestion[];
Fjerne det som har med searchSuggestions.

2021-11-16 10:20 UTC, oyvindis commented on src/components/with-suggestions/redux/actions.ts
> +export function resetSearchSuggestions() {
Den er ikke i bruk ser det ut som.

2021-11-16 10:21 UTC, oyvindis requested changes
Ser bra ut som du har gjort! Se kommentarer, jeg tror state kan forenkles noe og at du kun trenger den du har kalt cachedSuggestions.

2021-11-18 14:04 UTC, jeffreiffers approved these changes

2021-11-24 15:49 UTC, merged