Feat/mjs/dataset details page
datadeling/datafabrikken-portal pull request #52
Opened 2021-10-13 09:25 UTC by matsjs

Closes #32
Closes #33

2021-10-15 05:45 UTC, oyvindis commented on src/components/with-dataset/redux/reducer.ts
> +      return state.set('isLoadingDataset', false);
Må vel også sette state.set('dataset', null)

2021-10-15 05:56 UTC, oyvindis commented on src/components/details-page/components/inline-list/styled.ts
> +const List = styled.ul<{ column: boolean }>`
Man vil ikke ha denne prop med i dom, bruk da transient prop: const List = styled.ul<{ $column: boolean }>`

2021-10-15 05:59 UTC, oyvindis commented on src/components/details-page/components/themes/styled.ts
> +      background: white;
evt: background: ${theme.colour(Colour.NEUTRAL, 'N0')};

2021-10-15 06:06 UTC, oyvindis commented on src/entrypoints/main/router/pages/details-page-dataset/components/dataset-distribution/components/detail/styled.ts
> +  border-top: 1px solid #dfe1e2;
Finnes det en definert farge?

2021-10-15 06:26 UTC, oyvindis requested changes
Ser bra ut dette! Se noen kommentarer. 

I tillegg hvis du vil prøve på en git-øvelse. Det er en del commits i denne PR som er rettelser av foregående commits i samme PR. For den som tar review er det litt unødvendig å gjøre review av noe som er "kladd" i samme pr. Prøv å se om du kan organisere på nytt, squashe det som hører sammen.

2021-10-15 06:45 UTC, jeffreiffers commented on package.json
>      "showdown": "^1.9.1",
siden du bruker react-markdown kan showdown erstattes

2021-10-15 07:18 UTC, matsjs commented on src/components/key-value-list-item/styled.ts
> +  highlighted?: boolean;
Hvorfor med dollartegn foran?

2021-10-15 07:23 UTC, matsjs commented on src/components/details-page/components/content-section/styled.ts
> +  boxStyle?: boolean;
Skjønner, men hvorfor ikke? Den kolliderer jo ikke med noen html attributt?

2021-10-15 13:53 UTC, oyvindis commented on src/components/details-page/styled.ts
> +  flex-direction: row;
Du overrider denne, men test om du må sette denne tilbake til "column" i mobil-visning.

2021-10-18 05:58 UTC, oyvindis commented on src/components/details-page/components/side-menu/index.tsx
> +  <SC.SideMenu {...props}>
Hvorfor {...props} her?

2021-10-18 06:05 UTC, oyvindis commented on src/components/inline-list/styled.ts
> +  $bordered?: boolean;
Evt hasBorder mer lesbart?

2021-10-18 14:01 UTC, merged